#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

// 基本設定
#ifndef ENABLE_BLE
#define ENABLE_BLE
#endif

#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_CENTRAL
#define ENABLE_L2CAP_LE_CREDIT_BASED_FLOW_CONTROL_MODE
#define ENABLE_GATT_CLIENT
#define ENABLE_GATT_SERVER

#define HAVE_EMBEDDED_TIME_MS
#define HAVE_BTSTACK_STDIN
#define HAVE_HAL_AUDIO

// デバッグ設定
#define ENABLE_PRINTF_HEXDUMP

// Pico W (CYW43) 特有の設定
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_ACL_PAYLOAD_SIZE (251 + 4)
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4

// メモリ・データベース設定
#define HAVE_MALLOC
#define MAX_ATT_DB_SIZE 512
#define MAX_NR_LE_DEVICE_DB_ENTRIES 1
#define NVM_NUM_DEVICE_DB_ENTRIES   1
#define HAVE_BTSTACK_LE_DEVICE_DB_MEMORY // 今回追加：二重定義エラーを解消

// 接続リソース設定
#define MAX_NR_GATT_CLIENT_CHARACTERISTIC_WRITERS 1
#define MAX_NR_HCI_CONNECTIONS 1
#define MAX_NR_L2CAP_CHANNELS  2
#define MAX_NR_GATT_CLIENT_SERVER_IDS 1

// Security Manager
#define ENABLE_LE_SECURITY_MANAGER

#endif
